version: '3.7'

services:
  db:
    container_name: "library_db"
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./back-end/db.Dockerfile
    networks:
      - default
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_RANDOM_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=LibraryDB
      - MYSQL_TCP_PORT=3307
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=devtest
    ports:
      - 3307:3307
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  
  api:
    container_name: "library_api"
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./back-end/api.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./back-end:/app

networks:
  default:
volumes:
  mysql_data:
