version: '3.7'

services:
  db:
    container_name: "library_db"
    platform: linux/amd64
    build:
      context: ./src
      dockerfile: ./db.Dockerfile
    networks:
      - default
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=LibraryDB
      - MYSQL_TCP_PORT=3307
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=devtest
    ports:
      - 3307:3307
    volumes:
      - ./src/database/LibraryDB.sql:/data/application/LibraryDB.sql
    command: --init-file /data/application/LibraryDB.sql --character-set-server=utf8 --collation-server=utf8_general_ci

  api:
    container_name: "library_api"
    depends_on:
      - db
    build:
      context: ./src
      dockerfile: ./api.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/app

networks:
  default:
volumes:
  app: {}
